// <auto-generated />
using System;
using Mecario_BackEnd.DBContexs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mecario_BackEnd.Migrations
{
    [DbContext(typeof(ContextoBD))]
    [Migration("20251201065753_NewTable")]
    partial class NewTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Casos", b =>
                {
                    b.Property<int>("idCaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCaso"));

                    b.Property<string>("estadoCaso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("fechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<double>("horasTrabajadas")
                        .HasColumnType("float");

                    b.Property<int>("idOrdenServicio")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<double>("totalCaso")
                        .HasColumnType("float");

                    b.HasKey("idCaso");

                    b.HasIndex("idOrdenServicio");

                    b.HasIndex("idUsuario");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Clientes", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCliente"));

                    b.Property<string>("correoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("direccionCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCliente");

                    b.HasIndex("correoCliente")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.DetallesCaso", b =>
                {
                    b.Property<int>("idDetalleCaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDetalleCaso"));

                    b.Property<DateTime>("hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCaso")
                        .HasColumnType("int");

                    b.Property<string>("tareaRealizada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDetalleCaso");

                    b.HasIndex("idCaso");

                    b.ToTable("DetallesCasos");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.DetallesPiezas", b =>
                {
                    b.Property<int>("idCaso")
                        .HasColumnType("int");

                    b.Property<int>("idPieza")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<double>("precioUnitario")
                        .HasColumnType("float");

                    b.Property<double>("subtotal")
                        .HasColumnType("float");

                    b.HasKey("idCaso", "idPieza");

                    b.HasIndex("idPieza");

                    b.ToTable("DetallesPiezas");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.OrdenesServicio", b =>
                {
                    b.Property<int>("idOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idOrden"));

                    b.Property<double>("costoInicial")
                        .HasColumnType("float");

                    b.Property<string>("diagnosticoInicial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("tipoServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idOrden");

                    b.HasIndex("idVehiculo");

                    b.ToTable("OrdenesServicios");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Piezas", b =>
                {
                    b.Property<int>("idPieza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPieza"));

                    b.Property<string>("categoriaPieza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoPieza")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("descripcionPieza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombrePieza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precioUnidad")
                        .HasColumnType("float");

                    b.Property<int>("stockActual")
                        .HasColumnType("int");

                    b.HasKey("idPieza");

                    b.HasIndex("codigoPieza")
                        .IsUnique();

                    b.ToTable("Piezas");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.ServiciosMecanicos", b =>
                {
                    b.Property<int>("idServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idServicio"));

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("servicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idServicio");

                    b.ToTable("ServiciosMecanicos");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Usuarios", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("correoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("direccionUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUsuario");

                    b.HasIndex("correoUsuario")
                        .IsUnique();

                    b.HasIndex("userName")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Vehiculos", b =>
                {
                    b.Property<int>("idVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVehiculo"));

                    b.Property<int>("anio")
                        .HasColumnType("int");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroChasis")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("placa")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("idVehiculo");

                    b.HasIndex("idCliente");

                    b.HasIndex("numeroChasis")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("OrdenServicio_Servicio", b =>
                {
                    b.Property<int>("idOrden")
                        .HasColumnType("int");

                    b.Property<int>("idServicio")
                        .HasColumnType("int");

                    b.HasKey("idOrden", "idServicio");

                    b.HasIndex("idServicio");

                    b.ToTable("OrdenServicio_Servicio", (string)null);
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Casos", b =>
                {
                    b.HasOne("Mecario_BackEnd.Modelos.OrdenesServicio", "ordenesServicio")
                        .WithMany("casos")
                        .HasForeignKey("idOrdenServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecario_BackEnd.Modelos.Usuarios", "usuarios")
                        .WithMany("casos")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ordenesServicio");

                    b.Navigation("usuarios");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.DetallesCaso", b =>
                {
                    b.HasOne("Mecario_BackEnd.Modelos.Casos", "casos")
                        .WithMany("detallesCaso")
                        .HasForeignKey("idCaso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("casos");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.DetallesPiezas", b =>
                {
                    b.HasOne("Mecario_BackEnd.Modelos.Casos", "casos")
                        .WithMany("detallesPieza")
                        .HasForeignKey("idCaso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecario_BackEnd.Modelos.Piezas", "piezas")
                        .WithMany("detallesPieza")
                        .HasForeignKey("idPieza")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("casos");

                    b.Navigation("piezas");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.OrdenesServicio", b =>
                {
                    b.HasOne("Mecario_BackEnd.Modelos.Vehiculos", "vehiculos")
                        .WithMany("ordenesServicios")
                        .HasForeignKey("idVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vehiculos");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Vehiculos", b =>
                {
                    b.HasOne("Mecario_BackEnd.Modelos.Clientes", "Clientes")
                        .WithMany("Vehiculos")
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("OrdenServicio_Servicio", b =>
                {
                    b.HasOne("Mecario_BackEnd.Modelos.OrdenesServicio", null)
                        .WithMany()
                        .HasForeignKey("idOrden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mecario_BackEnd.Modelos.ServiciosMecanicos", null)
                        .WithMany()
                        .HasForeignKey("idServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Casos", b =>
                {
                    b.Navigation("detallesCaso");

                    b.Navigation("detallesPieza");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Clientes", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.OrdenesServicio", b =>
                {
                    b.Navigation("casos");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Piezas", b =>
                {
                    b.Navigation("detallesPieza");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Usuarios", b =>
                {
                    b.Navigation("casos");
                });

            modelBuilder.Entity("Mecario_BackEnd.Modelos.Vehiculos", b =>
                {
                    b.Navigation("ordenesServicios");
                });
#pragma warning restore 612, 618
        }
    }
}
